### ISSUE TITLE
Should we clear up the message when user attempts to install nonexistent template?

### ISSUE THREAD

**Issue by ryanisinallofus** [FormidableLabs/denim#8]
```
Error: Templates path '/var/folders/pw/zjw3gw9d0n99tgnmkgyb0hg80000gn/T/denim117115-4973-3qwh7u.t846phw7b9/extracted/templates' directory not found
    at /Users/r/.nvm/versions/node/v7.1.0/lib/node_modules/denim/lib/templates.js:200:15
    at /Users/r/.nvm/versions/node/v7.1.0/lib/node_modules/denim/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:111:15)
```

I suggest:

```
Denim template 'template you tried to install' not found.
```

**Comment by ryan-roemer** [comment]
It's actually a _programmer_ error to allow a user to install bad templates. And of course, all template module authors should be CI-ing their templates via dummy project creation.

I'm thinking more of something like `ERROR: templates directory `NAME` not found.`

**Comment by ryan-roemer** [comment]
haha, we already have that.
